apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: 355449129696.dkr.ecr.us-east-1.amazonaws.com/expense-{{ .Values.appName }}:{{ .Values.imageTag }}
        envFrom:
        - configMapRef:
            name: {{ .Values.appName }}
        ports:
        - containerPort: {{ .Values.port }}